spring.application.name=twitterfake

spring.datasource.url=jdbc:mysql://localhost:3306/twitterfake?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=root
spring.datasource.password=Mysqlsenha

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true